export const virement = [
  {
    numeroCompte: "061 0489590",
    cin: "Z163445",
    codeAgence: "",
    montantChiffre: "3  000,00",
    montantLettre: "TROIS  MILLE",
    nomClient: "CHOUALI SIHAM",
    beneficiaire: "LBQOUR  HADDA",
    statut: "manuelle",
    rouge: ["numeroCompte", "beneficiaire"],
  },
  {
    numeroCompte: "05253000480515",
    cin: "S258929",
    codeAgence: "",
    montantChiffre: "700,00",
    montantLettre: "SEPT  CENTS",
    nomClient: "EL  BARDAI  SAIDA",
    beneficiaire: "EL  BARDAI  EL  YAMANI",
    statut: "automatique",
  },
  {
    numeroCompte: "03482000489031",
    cin: "CC7965",
    codeAgence: "",
    montantChiffre: "1  500,00",
    montantLettre: "MILLE  CINQ CENTS",
    nomClient: "BOUAZZA  MOHAMMED",
    beneficiaire: "ZERRAD KHADIJA",
    statut: "automatique",
  },
  {
    numeroCompte: "01745000430625",
    cin: "D478007",
    codeAgence: "",
    montantChiffre: "5  000,00",
    montantLettre: "CINQ MILLE",
    nomClient: "BAADDI  FATIMA",
    beneficiaire: "BAADDI  YASSIR",
    statut: "automatique",
  },
  {
    numeroCompte: "04802000489304",
    cin: "DN16384",
    codeAgence: "",
    montantChiffre: "10  000,00",
    montantLettre: "DIX  MILLE",
    nomClient: "NAJIB  MOHAMED",
    beneficiaire: "NAJIB  ABDEL-ALI",
    statut: "automatique",
  },
  {
    numeroCompte: "03673000480085",
    cin: "B180961",
    codeAgence: "",
    montantChiffre: "10  000,00",
    montantLettre: "DIX  MILLE",
    nomClient: "SOUBOUL  FATIMA",
    beneficiaire: "BQUAOUD''AHMED'",
    statut: "manuelle",
    rouge: ["beneficiaire"],
  },
  {
    numeroCompte: "04882000459222",
    cin: "JE135997",
    codeAgence: "",
    montantChiffre: "3  500,00",
    montantLettre: "TROIS MILLE  CINQ  CENTS",
    nomClient: "GRIECH  AICHA",
    beneficiaire: "GRIECH  LAHCEN",
    statut: "automatique",
  },
  {
    numeroCompte: "04882000459222",
    cin: "BB172706",
    codeAgence: "",
    montantChiffre: "3  400,00",
    montantLettre: "TROIS  MILLE  QUATRE  CENTS",
    nomClient: "GRIECH  AICHA",
    beneficiaire: "GRIECH  HOUDA",
    statut: "automatique",
  },
  {
    numeroCompte: "00222000435011",
    cin: "G224565",
    codeAgence: "",
    montantChiffre: "1  300,00",
    montantLettre: "MILLE  TROIS  CENTS",
    nomClient: "LECHGAR  HAFIDA",
    beneficiaire: "LECHGAR  TOURIA",
    statut: "automatique",
  },
  {
    numeroCompte: "04189000489098",
    cin: "QA102583",
    codeAgence: "",
    montantChiffre: "1  000,00",
    montantLettre: "MILLE  DIRHAMS",
    nomClient: "ZINEDDAINE  ZAHRA",
    beneficiaire: "ZINEDDINE  NAJAT",
    statut: "automatique",
  },
  {
    numeroCompte: "06182000489049",
    cin: "LB39177",
    codeAgence: "",
    montantChiffre: "10  000,00",
    montantLettre: "DIX  MILLE",
    nomClient: "EL  ABIAD  BOUSSELHAM",
    beneficiaire: "EL  ABIAD   MUSTAPHA",
    statut: "automatique",
  },
  {
    numeroCompte: "04982000431051",
    cin: "P208471",
    codeAgence: "",
    montantChiffre: "4  000,00",
    montantLettre: "QUATRE  MILLE",
    nomClient: "OUANOU  MOHAMED",
    beneficiaire: "ALLAOUI  KELTOUMA",
    statut: "automatique",
  },
  {
    numeroCompte: "04882000459222",
    cin: "JE135997",
    codeAgence: "",
    montantChiffre: "3  500,00",
    montantLettre: "TROIS  MILLE  CINQ CENTS",
    nomClient: "GRIECH  AICHA",
    beneficiaire: "GRIECH  LAHCEN",
    statut: "automatique",
  },
  {
    numeroCompte: "13525000489035",
    cin: "U127962",
    codeAgence: "",
    montantChiffre: "6  500,00",
    montantLettre: "SIX  MILLE  CINQ  CENTS",
    nomClient: "HOIWIR  BABA  OMAR",
    beneficiaire: "HOIWIR  GHZALA",
    statut: "automatique",
  },
  {
    numeroCompte: "04837000430826",
    cin: "D368745",
    codeAgence: "",
    montantChiffre: "7  500,00",
    montantLettre: "SEPT  MILLE  CINQ  CENTS",
    nomClient: "ANBOUSSE' 'RACHID'",
    beneficiaire: "ANBQUSSE' 'HAFID'",
    statut: "automatique",
  },
  {
    numeroCompte: "09979000430212",
    cin: "MAROC",
    codeAgence: "",
    montantChiffre: "5  000,00",
    montantLettre: "CINQ  MILLE",
    nomClient: "ALQUI  ABDELHAMID",
    beneficiaire: "ALOUI  OTMAN",
    statut: "manuelle",
    rouge: ["nomClient"],
  },
  {
    numeroCompte: "00422000431736",
    cin: "GK40462",
    codeAgence: "",
    montantChiffre: "6  000,00",
    montantLettre: "SIX  MILLE",
    nomClient: "SAYED  AMINA",
    beneficiaire: "SAYED  HANAE",
    statut: "automatique",
  },
  {
    numeroCompte: "13534000480212",
    cin: "P79265",
    codeAgence: "",
    montantChiffre: "10  000,00",
    montantLettre: "DIX  MILLE",
    nomClient: "EL  HADDYOUY  OUSSAADANC'",
    beneficiaire: "EL  HADDYOUY  BRAHIM",
    statut: "manuelle",
    rouge: ["nomClient"],
  },
  {
    numeroCompte: "13798000193336",
    cin: "MC208518",
    codeAgence: "",
    montantChiffre: "2  000,00",
    montantLettre: "DEUX  MILLE",
    nomClient: "KH   MED",
    beneficiaire: "KHOULI  BOUCHAIB",
    statut: "manuelle",
    rouge: ["nomClient"],
  },
  {
    numeroCompte: "03765000471004",
    cin: "BB15101",
    codeAgence: "",
    montantChiffre: "5  000,00",
    montantLettre: "CINQ  MILLE  DIRHAMS",
    nomClient: "CHATTAHY   ABDELHAK",
    beneficiaire: "CHATTAHY  NAIMA",
    statut: "automatique",
  },
  {
    numeroCompte: "04064000458455",
    cin: "'Q139016'",
    codeAgence: "",
    montantChiffre: "10  000,00",
    montantLettre: "DIX''MILLE'",
    nomClient: "SENNI''EL''KBIR'",
    beneficiaire: "SENNI''EL''RHAZOUANI'",
    statut: "automatique",
  },
];
